/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jp.liferay.google.drive.search.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the GoogleDriveSearch service. Represents a row in the &quot;GD_GoogleDriveSearch&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>jp.liferay.google.drive.search.model.impl.GoogleDriveSearchModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>jp.liferay.google.drive.search.model.impl.GoogleDriveSearchImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GoogleDriveSearch
 * @generated
 */
@ProviderType
public interface GoogleDriveSearchModel extends BaseModel<GoogleDriveSearch> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a google drive search model instance should use the {@link GoogleDriveSearch} interface instead.
	 */

	/**
	 * Returns the primary key of this google drive search.
	 *
	 * @return the primary key of this google drive search
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this google drive search.
	 *
	 * @param primaryKey the primary key of this google drive search
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the gd ID of this google drive search.
	 *
	 * @return the gd ID of this google drive search
	 */
	public long getGdId();

	/**
	 * Sets the gd ID of this google drive search.
	 *
	 * @param gdId the gd ID of this google drive search
	 */
	public void setGdId(long gdId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		jp.liferay.google.drive.search.model.GoogleDriveSearch
			googleDriveSearch);

	@Override
	public int hashCode();

	@Override
	public CacheModel<jp.liferay.google.drive.search.model.GoogleDriveSearch>
		toCacheModel();

	@Override
	public jp.liferay.google.drive.search.model.GoogleDriveSearch
		toEscapedModel();

	@Override
	public jp.liferay.google.drive.search.model.GoogleDriveSearch
		toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}