/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package jp.liferay.google.drive.search.model.impl;

import aQute.bnd.annotation.ProviderType;

import jp.liferay.google.drive.search.model.GoogleDriveSearch;
import jp.liferay.google.drive.search.service.GoogleDriveSearchLocalServiceUtil;

/**
 * The extended model base implementation for the GoogleDriveSearch service. Represents a row in the &quot;GD_GoogleDriveSearch&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link GoogleDriveSearchImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GoogleDriveSearchImpl
 * @see GoogleDriveSearch
 * @generated
 */
@ProviderType
public abstract class GoogleDriveSearchBaseImpl
	extends GoogleDriveSearchModelImpl implements GoogleDriveSearch {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a google drive search model instance should use the <code>GoogleDriveSearch</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			GoogleDriveSearchLocalServiceUtil.addGoogleDriveSearch(this);
		}
		else {
			GoogleDriveSearchLocalServiceUtil.updateGoogleDriveSearch(this);
		}
	}

}